name: Run Tests and Deploy Pages

on: workflow_dispatch 

jobs:
  api_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name:  Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run api tests via docker-compose
        run: |
          docker compose up api-tests --exit-code-from api-tests || true

      # - name: Copy history from gh-pages to allure-results
      #   run: |
      #     sudo mkdir -p allure-results/history # Создает директорию для истории Allure
      #     sudo cp -R ./.github/gh-pages/history/* allure-results/history/

      - name: Generate Allure report
        run: |
          sudo docker compose run report

      # - name: Update Allure history
      #   run: |
      #     sudo cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
